# GENERATE TIME: Sat Jun  3 09:53:12 2023
# CMD:
# basicsr/train.py -opt options/train/SAFMN/4xHFA2kLUDVAESAFMN.yml

# general settings
# Claculate on 720P
# Params: 0.24M, FLOPs: 13.555G, Activations: 76.7M
name: 4xHFA2kLUDVAESAFMN
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: HFA2k_LUDVAE
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2k_LUDVAE/HR 
    dataroot_lq: /home/phips/Documents/datasets/HFA2k_LUDVAE/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 40
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  # we use multiple validation datasets. The SR benchmark datasets can be download from: https://cv.snu.ac.kr/research/EDSR/benchmark.tar
  val:
    name: DIV2K_val100
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2k_LUDVAE/VAL_HR
    dataroot_lq: /home/phips/Documents/datasets/HFA2k_LUDVAE/VAL_LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
      
# network structures
network_g:
  type: SAFMN
  dim: 36
  n_blocks: 8
  ffn_scale: 2.0
  upscaling_factor: 4

# path
path:
  pretrain_network_g: /home/phips/Documents/SAFMN/experiments/pretrain/net_g_152000.pth
  strict_load_g: false
  resume_state: /home/phips/Documents/SAFMN/experiments/pretrain/152000.state
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: 1000
  save_img: True
  pbar: True

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: False
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: False
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
